[package]
name = "folio-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }