[package]
name = "folio-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
strum = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }