[package]
name = "folio-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
folio-core = { path = "../folio-core" }
folio-storage = { path = "../folio-storage" }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
