[package]
name = "folio-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
folio-core = { path = "../folio-core" }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }